### ISSUE TITLE
[feat] 캐러셀 구현

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/tbwa-kukka#1]
# TASK CARD

Task Description : 버튼을 누르면 메인 이미지 및 사이드 이미지가 바뀌는 캐러셀 구현

Date : 2022-02-21

## to-do

- [x] 각 이미지 별로 해당 이미지 관련 정보를 담은 객체 구현
- [x] 메인 이미지, 사이드 이미지용 CSS 만들기
- [x] 사진 넘기기용 버튼 스타일링 + 기능 구현
- [ ] 자동으로 사진이 일정 간격으로 넘어가는 기능 구현
